// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// kmnsw
Rcpp::List kmnsw(Rcpp::NumericMatrix a_R, Rcpp::NumericMatrix c_R, Rcpp::NumericVector wh_R, int k, int iter);
RcppExport SEXP stream_kmnsw(SEXP a_RSEXP, SEXP c_RSEXP, SEXP wh_RSEXP, SEXP kSEXP, SEXP iterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type a_R(a_RSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type c_R(c_RSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type wh_R(wh_RSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type iter(iterSEXP);
    rcpp_result_gen = Rcpp::wrap(kmnsw(a_R, c_R, wh_R, k, iter));
    return rcpp_result_gen;
END_RCPP
}
