# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

shc_MDSeparation <- function(mean1, covariance1, virtualVariance1, N1, isInversion1, th1, mean2, covariance2, virtualVariance2, N2, isInversion2, th2) {
    .Call(`_stream_shc_MDSeparation`, mean1, covariance1, virtualVariance1, N1, isInversion1, th1, mean2, covariance2, virtualVariance2, N2, isInversion2, th2)
}

shc_MutualMinMahalanobis <- function(mean1, covariance1, virtualVariance1, N1, isInversion1, mean2, covariance2, virtualVariance2, N2, isInversion2) {
    .Call(`_stream_shc_MutualMinMahalanobis`, mean1, covariance1, virtualVariance1, N1, isInversion1, mean2, covariance2, virtualVariance2, N2, isInversion2)
}

shc_CalculateNewMean <- function(mean, newElement, N) {
    .Call(`_stream_shc_CalculateNewMean`, mean, newElement, N)
}

shc_CalculateCovariance <- function(oldMean, newMean, oldCovariance, N, newElement, isInversion) {
    .Call(`_stream_shc_CalculateCovariance`, oldMean, newMean, oldCovariance, N, newElement, isInversion)
}

kmnsw <- function(a_R, c_R, wh_R, k, iter) {
    .Call(`_stream_kmnsw`, a_R, c_R, wh_R, k, iter)
}

